let lastTimestamp = 0;

async function checkBrain() {
    try {
        // Read the state file generated by maya_brain.js
        const response = await fetch('maya_state.json');
        const data = await response.json();

        // If the timestamp is new, trigger the animation
        if (data.timestamp !== lastTimestamp) {
            lastTimestamp = data.timestamp;
            updateDisplay(data.message, data.mood);
        }
    } catch (e) {
        console.log("Maya is sleeping...");
    }
}

function updateDisplay(text, mood) {
    const bubble = document.getElementById('maya-speech-bubble');
    const textSpan = document.getElementById('maya-text');
    const moodDisplay = document.getElementById('current-mood');

    // Update Status
    moodDisplay.innerText = `STATUS: ${mood.toUpperCase()}`;

    // Show Bubble
    bubble.classList.remove('hidden');
    textSpan.innerText = ""; // Clear previous text

    // Typewriter Effect
    let i = 0;
    const speed = 50; // typing speed in ms

    function typeWriter() {
        if (i < text.length) {
            textSpan.innerHTML += text.charAt(i);
            i++;
            setTimeout(typeWriter, speed);
        } else {
            // Text finished. Wait 10 seconds then fade out.
            setTimeout(() => {
                bubble.classList.add('hidden');
            }, 10000);
        }
    }
    
    typeWriter();
}

// Poll the brain file every 1 second
setInterval(checkBrain, 1000);
updateClock(); // From previous code
